---
branches:
  - main
  - name: dev
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  -   - '@semantic-release/exec'
      - prepareCmd: perl -i -p0e 's/(\nname[[:space:]]*=[[:space:]]*"syntropic-api"\nversion[[:space:]]*=[[:space:]]*)(.*)\n/\1"${nextRelease.version}"\n/'
          Cargo.toml Cargo.lock
  -   - '@semantic-release/git'
      - assets: [Cargo.toml, Cargo.lock, CHANGELOG.md]
  - '@semantic-release/github'
