---
branches:
  - main
  - name: dev
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  -   - '@semantic-release/exec'
      - prepareCmd: sed -E -i -e "s/^(version[[:space:]]*=[[:space:]]*)(.*)$/\1\"${nextRelease.version}\"/"
          Cargo.toml
  -   - '@semantic-release/git'
      - assets: [Cargo.toml, CHANGELOG.md]
  - '@semantic-release/github'
